apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-prom-deployment
  namespace: default
  labels:
    app: go-prom
spec:
  replicas: 1
  template:
    metadata:
      name: go-prom
      labels:
        app: go-prom
    spec:
      containers:
        - name: go-prom
          image: hown3d/go-prom:1.0.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: go-prom
